ACTION ReadVarsFromHMI: (* Preberi vse spremenljivke iz HMI ekrana *)
	// Dummy
	diHMIin1 := diHMIin1;
	
	// Agregat
	agr1 := agr1;
	agr2 := agr2;
	agr3 := agr3;
	agr4 := agr4;
	agr5 := agr5;
	agr6 := agr6;
	
	diPozAgrOK := diPozAgrOK;
	
	diSTEP := diSTEP;
	diPrekiniCikel := diPrekiniCikel;
	diSoftStop := diSoftStop;
	diStartStroja := diStartStroja;
	doDelovanje := doDelovanje;
	diRand := diRand;
	diSetAgrPoz := diSetAgrPoz;
	diGoHome := diGoHome;
	doFunSuccess := doFunSuccess;
	doHMIout1 := doHMIout1;
	diPotrdiPozicije := diPotrdiPozicije;
	diShraniPozicije := diShraniPozicije;
	doStrojPripravljen := doStrojPripravljen;
	izbrani_agr := izbrani_agr;
	
	vozicek := vozicek;

	
	diHMIin1 := diHMIin1;
	diHMIin2 := diHMIin2;
	
	(*
	agr1.agr_active := agr1.agr_active;
	agr2.agr_active := agr2.agr_active;
	agr3.agr_active := agr3.agr_active;
	agr4.agr_active := agr4.agr_active;
	agr5.agr_active := agr5.agr_active;
	agr6.agr_active := agr6.agr_active;
	

	
	agr1.poz_agr_s := agr1.poz_agr_s;
	agr2.poz_agr_s := agr2.poz_agr_s;
	agr3.poz_agr_s := agr3.poz_agr_s;
	agr4.poz_agr_s := agr4.poz_agr_s;
	agr5.poz_agr_s := agr5.poz_agr_s;
	agr6.poz_agr_s := agr6.poz_agr_s;
	*)
END_ACTION